LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of Pokémon.\p"
    .string "Memorial services are held in\n"
    .string "Pokémon TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Ghosts appeared in Pokémon TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "Pokémon that the ROCKETS killed.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice::
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER VOLUNTEER\n"
    .string "Pokémon HOUSE$"

LavenderTown_Text_PokemonTowerSign::
    .string "Pokémon TOWER\n"
    .string "Becalm the Spirits of Pokémon$"

