FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "You can't become a good TRAINER\n"
    .string "with just one strong Pokémon.\p"
    .string "But raising many Pokémon evenly\n"
    .string "is no easy task, either.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "There's a narrow trail west of\n"
    .string "VIRIDIAN CITY.\p"
    .string "It goes to the Pokémon LEAGUE HQ.\n"
    .string "The HQ governs all TRAINERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "If you're working on a Pokédex,\n"
    .string "visit the SAFARI ZONE.\p"
    .string "All sorts of rare Pokémon breed\n"
    .string "there.$"

