CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL not only keeps bugs away,\n"
    .string "it also works on weak Pokémon.\p"
    .string "Put your strongest Pokémon at the\n"
    .string "left of the Pokémon LIST.\p"
    .string "If your first Pokémon is strong,\n"
    .string "REPEL's effect is boosted.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Do you know about RARE CANDY?\n"
    .string "They don't sell it in shops.\p"
    .string "I think it makes Pokémon grow\n"
    .string "very quickly all of a sudden.$"

